# Generated by Django 5.0.4 on 2024-04-05 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=250)),
                ('descricao', models.CharField(max_length=500)),
                ('em_equipamento', models.BooleanField(default=True)),
                ('idade_minima_aluno', models.PositiveIntegerField(default=12)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treinos.exercicio')),
            ],
        ),
        migrations.CreateModel(
            name='Treino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('exercicios', models.ManyToManyField(through='treinos.Item', to='treinos.exercicio')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='treino',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='treinos.treino'),
        ),
    ]
